### ISSUE TITLE
Saving a large section leads to stalled task when using Preparse for image transforms.

### ISSUE THREAD

**Issue by janson** [aelvan/Preparse-Field-Craft#28]
The plugin's idea is wonderful, but I'm having trouble adding it retroactively to a site. 

- I've added a preparse field, which generates 3 transforms for an entry's asset field:

```
{% if entry.photos|length > 0 %}
    {% for photo in entry.photos %}
        {{ photo.url('thumb') }}
        {{ photo.url('lqip') }}
        {{ photo.url('square') }}
    {% endfor %}
{% endif %}
```

- When saving a section's settings, Craft re-saves all the elements in that section (`SectionsService:L717` via a background task `ResaveElementsTask`).
- Doing this in a section with a decent number of entries (>250) the task hits the PHP memory limit and stalls, leaving the site with half-updated section entries. 

I understand that adding overhead to a save by transforming an elements images is hard on a server. But this seems like a pretty common use case for preparse (images) and scenario (the dev needs to update a Section's setting), so I'm wondering if anyone has experienced this and has any ideas before I dig into preparse' code.

**Comment by janson** [comment]
Perhaps indirectly related to #27

**Comment by aelvan** [comment]
This doesn't really have anything to do with Preparse Field. Of course, parsing that twig on save, resulting in the server having to do multiple image resizes, saving transforms to the database, etc – in addition to the fact that Preparse makes the element save twice as stated in #27 (although, on the second pass, the transforms would already be created so it'll be a much faster save) – doesn't help. But the underlying problem is 1) that Craft re-saves elements when you update a section, and 2) that the task system in Craft is really prone to dying. 

There's really not much to do other than either leave things as they are, or up the memory and execution limits on the server enough that it doesn't time out.
