### ISSUE TITLE
Matrix row is deleted on save

### ISSUE THREAD

**Issue by tinchalamo** [aelvan/Preparse-Field-Craft#46]
I have a matrix field with two block types: Format HO Codes and Session ID. The Format HO Codes block is using a Super Table field and the Session ID block is using a plain text field.

I created a Preparse Field that saves the data of a Session ID block type into a separate field:

`{% for block in entry.vistaCode.type('sessionId').all() %}{{ block.theater.one.vistaId }}_{{ block.sessionId }}{% endfor %}`

The problem I've run into is that I can no longer use the Format HO Codes block type since the data disappears on save and the Format HO Codes block type is no longer showing up in entries that were using it.

**Comment by aelvan** [comment]
Not sure I follow which fields in the code you're referring to. But most likely this is due to you manipulating element queries that is used by Craft at a later point, directly. In your code, `entry.vistaCode` and `block.theater`are element queries, and when you set `type` for instance, that just manipulates the element query, it doesn't make/clone a new one. So when Craft tries to access the same element query later, it will continue to use the manipulated one.

This was new in Craft 3, and the solution is to manually clone the queries before using them.

See:
https://docs.craftcms.com/v3/changes-in-craft-3.html#element-queries
https://github.com/aelvan/Preparse-Field-Craft/issues/36
